<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * Auto-generated by BlueprintScaffoldService: registers every
     * Blueprint-generated seeder in dependency order (parents first).
     */
    public function run(): void
    {
        $this->call([
            McpServerSeeder::class,
            McpToolSeeder::class,
            WebhookEndpointSeeder::class,
            WebhookDeliverySeeder::class,
            ConversationSeeder::class,
            ChatMessageSeeder::class,
            AgentTaskSeeder::class,
            VillaSeeder::class,
            VillaRateSeeder::class,
            VillaBookingSeeder::class,
            TaxiSeeder::class,
            TaxiBookingSeeder::class,
            RestaurantSeeder::class,
            RestaurantBookingSeeder::class,
            WinerySeeder::class,
            WineryVisitSeeder::class,
            TourSeeder::class,
            TourBookingSeeder::class,
            ProductCategorySeeder::class,
            ProductSeeder::class,
            OrderSeeder::class,
            OrderItemSeeder::class,
            ItinerarySeeder::class,
            ItineraryItemSeeder::class,
            PaymentSeeder::class,
            InvoiceSeeder::class,
        ]);
    }
}
